apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: festivalsync
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # salva i dati localmente.
    path: /mnt/data/mariadb
