services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: festivalsyncDB
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - db_network


  zookeeper:
    image: bitnami/zookeeper:latest  # Immagine aggiornata di Zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # Permette il login anonimo per scopi di test
    networks:
      - db_network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - db_network
    depends_on:
      - zookeeper

  # Micro-servizio artist-service
  artist-service:
    image: artist-service:latest
    build: ./artist-service
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/festivalsyncDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - db_network
    depends_on:
      - kafka

  # Micro-servizio event-service
  event-service:
    image: event-service:latest
    build: ./event-service
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/festivalsyncDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - db_network
    depends_on:
      - kafka

  # Micro-servizio ticket-service
  ticket-service:
    image: ticket-service:latest
    build: ./ticket-service
    ports:
      - "8083:8083"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/festivalsyncDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - db_network
    depends_on:
      - kafka
  gateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    networks:
      - db_network
    depends_on:
      - artist-service
      - event-service
      - ticket-service
volumes:
  mariadb_data:

networks:
  db_network:
    driver: bridge