apiVersion: v1
kind: Service
metadata:
  name: mariadb-service # Nome del Service
  namespace: festivalsync
  labels:
    app: mariadb
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      nodePort: 32000  # Porta esposta sul nodo
  selector:
    app: mariadb # Associa il servizio ai pod con questa etichetta
