apiVersion: v1
kind: Service
metadata:
  name: mariadb-service # Nome del Service
  namespace: festivalsync
  labels:
    app: mariadb
spec:
  type: ClusterIP # Visibile solo all'interno del cluster
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mariadb # Associa il servizio ai pod con questa etichetta
