apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: festivalsync
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"  # Permette il login anonimo per test
          ports:
            - containerPort: 2181
