global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://cadvisor:8085
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: 'artist-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'artist-service:8081' ]
  - job_name: 'event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'event-service:8082' ]
  - job_name: 'ticket-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'ticket-service:8083' ]
