apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-service
  namespace: festivalsync
  labels:
    app: artist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artist-service
  template:
    metadata:
      labels:
        app: artist-service
    spec:
      containers:
        - name: artist-service
          image: artist-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: artist-service
  labels:
    app: artist-service
spec:
  selector:
    app: artist-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
